version: '3.9'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: openai@2023
      POSTGRES_USER: openai
      POSTGRES_DB: openai_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  elasticsearch-data:
