version: '3.9'
services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: openai@2023
      POSTGRES_USER: openai
      POSTGRES_DB: openai_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
